### ISSUE TITLE
The pre-filled definition URL in swagger UI is incorrect. 

### ISSUE THREAD

**Issue by niranjan94** [fastify/fastify-swagger-ui#11]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.8.1

### Plugin version

1.0.2

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.6

### Description

- The URL of the definition json pre-filled on the swagger UI is incorrect and has an extra `static` path component in it.
- Pre-filled: `http://127.0.0.1:8080/docs/static/json`. Expected: `http://127.0.0.1:8080/docs/json`

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/2404372/195042091-88221a40-f746-4f67-b3e2-dbe736d11cc3.png">

### Steps to Reproduce

```js
await fastify.register(require('@fastify/swagger'), {
    mode: 'dynamic',
    openapi: {
      info: {
        title: 'api.example.io',
        description: 'Example API',
        version: packageJson.version,
      },
      components: {
        securitySchemes: {
          apiKey: {
            description: 'Your API Key',
            type: 'apiKey',
            name: 'Authorization',
            in: 'header',
          },
        },
      },
    },
    hideUntagged: true,
  })

await fastify.register(require('@fastify/swagger-ui'), {
    routePrefix: '/docs',
    uiConfig: {
      deepLinking: true,
      filter: '',
    },
  })
```

And goto `http://127.0.0.1:8080/docs`

**Comment by Uzlopak** [comment]
PR #12 should fix that.
