### ISSUE TITLE
docs: advice about @fastify/swagger version support in the README.md

### ISSUE THREAD

**Issue by RodrigoDornelles** [fastify/fastify-swagger-ui#120]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

2.1.0

### Node.js version

20.1

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Linux 8a34e6999b2a 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 Linux

### Description

```
FastifyError [Error]: The decorator 'swaggerCSP' has already been added!
    at decorate (/app/node_modules/fastify/lib/decorate.js:23:11)
    at Object.decorateFastify [as decorate] (/app/node_modules/fastify/lib/decorate.js:67:3)
    at fastifySwaggerUi (/app/node_modules/@fastify/swagger-ui/index.js:11:11) {
  code: 'FST_ERR_DEC_ALREADY_PRESENT',
  statusCode: 500
}
```

### Steps to Reproduce

```typescript
import fastify from 'fastify';
import fastifySwagger from '@fastify/swagger';
import fastifySwaggerUI from '@fastify/swagger-ui';

const app = fastify();

app.register(fastifySwagger)
app.register(fastifySwaggerUI, {
  routePrefix: '/docs',
});

app.get('/', async (request, reply) => {
  return { hello: 'world!' };
});

app.ready()
```

### Expected Behavior

work without errors

**Comment by Uzlopak** [comment]
Maybe you use an old @fastify/swagger version. Can you provide a repo with an example project please?

**Comment by RodrigoDornelles** [comment]
That's right, it works with version 8 and there is a problem with version 7!

@Uzlopak  a suggestion before closing my issue would be a friendly error message, if the lifecycle allows it.

**Comment by Uzlopak** [comment]
That error message comes from fastify core. Maybe the solution is to write that we this plugin needs atleast fastify swagger v. x

**Comment by Uzlopak** [comment]
Reopening as we did not solve this documentation issue, yet ;)
