### ISSUE TITLE
"Unable to render this definition" on refreshing the page

### ISSUE THREAD

**Issue by blue86321** [fastify/fastify-swagger-ui#158]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.1

### Plugin version

4.0.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

In swagger docs, when unfolding the api difinitions, browser location (url) will change.

At this point, if we refresh the page, we will get error `Unable to render this definition`

It is because we find the **difinition** by using the current url and attach `./json`, e.g. `http://127.0.0.1:3000/api/docs#/auth/post_v1_auth_login/./json`

<img width="1433" alt="image" src="https://github.com/fastify/fastify-swagger-ui/assets/50546951/f844310e-b03d-4f4d-9f05-47acd53bfb28">

To resolve this bug, the most straightforward way is to modify the `swagger-initialzer.js`
(but this solution doesn't handle the corner case where the user's url contains `#`)
```diff
function resolveUrl(url) {
      var currentHref = window.location.href;
>     currentHref = currentHref.split('#')[0];
      currentHref = currentHref.endsWith('/') ? currentHref : currentHref + '/';
      var anchor = document.createElement('a');
      anchor.href = currentHref + url;
      return anchor.href
    }
```

A better way is to make it unchanged even we refresh the page, not sure if it is a big change or not.
What do you think?

### Expected Behavior

unfolding the API difinition, then refresh the browser, the docs stay the same instead of showing `Unable to render this definition`

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by blue86321** [comment]
> Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Done. I use the initial suggestion to solve it.
Seems like a hash `#` won't show up in a normal domain / url since it represents an anchor.

The PR is attached #160. Let me know if there is anything I can do.
