### ISSUE TITLE
Verify availability release version 1.1.0

### ISSUE THREAD

**Issue by leandroandrade** [fastify/fastify-swagger-ui#16]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I'm trying to install the new release `npm i @fastify/swagger-ui@1.1.0` but apparently it's not available. Is it possible to verify if something was missed in the release process?

![image](https://user-images.githubusercontent.com/2390150/196244431-2836005a-eda6-4c3f-b230-6a78742669ac.png)

* node: 16.18.0

Thanks!!!

**Comment by kibertoad** [comment]
@climba03003

**Comment by mcollina** [comment]
published

**Comment by climba03003** [comment]
Oh, I changed my default registry to private one.
It published to my private registry.
