### ISSUE TITLE
plugin config `routePrefix` breaks the page

### ISSUE THREAD

**Issue by blue86321** [fastify/fastify-swagger-ui#165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Plugin version

4.0.1

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

When we config the `routePrefix` parameter like below

```js
import { fastifySwaggerUi } from "@fastify/swagger-ui";
fastify.register(fastifySwaggerUi, { routePrefix: "/api/docs" })
```

- It breaks the documentation page as the css/js resource **double** the `api` prefix.
  <img width="1346" alt="image" src="https://github.com/user-attachments/assets/8d64ac66-82a2-443a-9621-123141b0c7e5">

- The resource can be visited by manually twisting the url
  <img width="502" alt="image" src="https://github.com/user-attachments/assets/b5f85d47-6794-48e6-89a3-691d84cdf46a">

- Removing the `routePrefix`, the documentation can be rendered correctly
  <img width="700" alt="image" src="https://github.com/user-attachments/assets/3570a4b6-01a7-4872-9170-40bcfe8b4f0b">

### Expected Behavior

The documentation page should be rendered correctly even with `routePrefix` config

**Comment by blue86321** [comment]
It works on version `4.0.0`, I doubt it's because of this PR #164

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
