### ISSUE TITLE
Allow onSend hook to mutate swagger object for each request (multi-tenant hosting)

### ISSUE THREAD

**Issue by jonaskello** [fastify/fastify-swagger-ui#18]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

This is a follow-up to [fastify-swagger#683](https://github.com/fastify/fastify-swagger/issues/683).

I have the same need as in https://github.com/fastify/fastify-swagger/pull/92 of setting the authorizationUrl but based not only on the hosting environment but also on the request. The app I have is multi-tenant and each tenant has a different authorizationUrl. Which tenant is calling is determined by the domain.

### Motivation

I don't think this can be achieved with the current postProcessor() introduced in https://github.com/fastify/fastify-swagger/pull/92 since it only runs once at setup.

### Example

For example calling `tenant1.myapp.com/theservice/docs` means that the `authorizationUrl` should be something like `https://login.myapp.com/auth/realms/tenant1/protocol/openid-connect/auth`.

Calling `tenant2.myapp.com/theservice/docs` means that the `authorizationUrl` should be something like `https://login.myapp.com/auth/realms/tenant2/protocol/openid-connect/auth`.

**Comment by Uzlopak** [comment]
Merged transformSpecification. Will be part of next release

**Comment by climba03003** [comment]
Released in 38a0de291058bf2f2a316ec2570eec950704360a
