### ISSUE TITLE
Issue with index html resources paths when using a complex path as route prefix

### ISSUE THREAD

**Issue by jpb06** [fastify/fastify-swagger-ui#180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

5.1.0

### Node.js version

20.18

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

15.0.1

### Description

It's appears [#178](https://github.com/fastify/fastify-swagger-ui/pull/178) is causing an issue when using a complex path in `routePrefix`, ie:

```ts
await this.instance.register(fastifySwaggerUI, {
  routePrefix: '/api/vi/$docs'
});
```

The resolved path looks like `/api/v1/api/v1/$docs/static` in that case.

<img width="821" alt="image" src="https://github.com/user-attachments/assets/a5e4d273-f075-418f-b636-c2c1115b50fb">

See linked repo for MRE.

### Link to code that reproduces the bug

https://github.com/jpb06/fastify-swagger-ui-routeprefix-issue-repro

### Expected Behavior

index resources to load properly.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jpb06** [comment]
Hello.

I spent some time yesterday trying to solve the issue while retaining the behavior wanted by @DavidTanner. Sadly I'm needed elsewhere so I won't have much time to investigate further.

**Comment by semy** [comment]
Please can you fix that? Have the same problem:
Instead of
`const prefix = hasTrailingSlash ? `.${opts.staticPrefix}` : `${hasLeadingSlash ? '.' : ''}${opts.prefix}${opts.staticPrefix}``

should be something like that...
`const prefix = hasTrailingSlash ? `.${opts.staticPrefix}` : `${hasLeadingSlash ? '' : '/'}${opts.prefix}${opts.staticPrefix}``

Sorry, but the code is pretty ambiguous anyway, I would generally go over it...

**Comment by ronielli** [comment]
How do I solve this problem, I still can't?

**Comment by DavidTanner** [comment]
Correct me if I'm wrong, but it kind of seems like this is a bad setup of the server.  Can someone please post a test example?  I'm going to try recreating in the project as well.

My first thought is that the fastify instance is already using that route prefix, and then you are specifying it again in the swagger config.  Again, that is my first thought and I could totally be wrong.

**Comment by DavidTanner** [comment]
I figured out the issue, and will create a PR to fix.  I need to add a new parameter to specify a prefix that only affects the index.html file.

**Comment by ronielli** [comment]
Good morning, everyone. Do you have an estimated time to approve this pull request?

**Comment by rozzilla** [comment]
FYI => https://github.com/fastify/fastify-swagger-ui/pull/189

**Comment by ronielli** [comment]
@rozzilla @DavidTanner Thank you so much! I just tested it, and everything is working perfectly. Great job! 😊

**Comment by jpb06** [comment]
Resolved on our side as well, thank you!

**Comment by MikaKarjunen** [comment]
The previous version worked exactly as intended using relative paths. Now, I don’t quite understand how we’re supposed to proceed with this solution. If the application is run during development at, say, localhost:3000/help, and on the server at foo.com/myapi/v1/help, how can this combination be made to work? I don’t think it makes sense for the application to dictate where it is essentially 'parked' in terms of routing. Or am I missing something? I guess I am, could you fellows push me to a right direction?

**Comment by DavidTanner** [comment]
@MikaKarjunen I have that same issue with dev vs production. I have an environment variable that I key off of for production that sets the prefix when deploying.  

My first suggestion would be to set the indexPrefix to v1 using some env variable that is only set in the deployed environments.

**Comment by MikaKarjunen** [comment]
> @MikaKarjunen I have that same issue with dev vs production. I have an environment variable that I key off of for production that sets the prefix when deploying.
> 
> My first suggestion would be to set the indexPrefix to v1 using some env variable that is only set in the deployed environments.

This is exactly what I was afraid of. We can make it work like this but it's not exactly what I would've liked to hear.

**Comment by DavidTanner** [comment]
You get my wheels spinning. We could propose an additional config option for the index to use relative paths.

**Comment by MikaKarjunen** [comment]
> You get my wheels spinning. We could propose an additional config option for the index to use relative paths.

That would solve this nicely David. We'd much appreciate it and I suppose so would other people as well.
