### ISSUE TITLE
Support object model for multiple, named examples

### ISSUE THREAD

**Issue by jschuur** [fastify/fastify-swagger-ui#21]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support using named examples via the object definition of `examples` rather than just an array.

### Motivation

If multiple examples are present, this would show a name in the examples drop down menu under 'Responses', rather than just 'example1', 'example2' etc. The `summary` field would then also show further details on the specific example.

### Example

`fastify-swagger-ui` should support the object format for `examples`, where you can name individual options:

```js
examples: {
  'first example': {
    value: 'abc',
    summary: 'Brief description of the first example'
  },
  'second example': {
    value: 'def',
    summary: 'Brief description of the second example'
  }
}
```

Currenrtly if you use this now, you (expectedly) get an error:

```
Failed building the serialization schema for GET: /api/v1/foo,due to error schema is invalid: data/examples must be array
```

There is some discussion of this [here](https://github.com/fastify/fastify-swagger/issues/625), but I can't quite grok it. Is the object `examples` format an OpenAPI 3.1 thing and it's not quite supported by `fastify-swagger` yet due to some kind of conflict?

**Comment by mcollina** [comment]
I think we only need somebody to do the work.

**Comment by Uzlopak** [comment]
I dont think that this is related to this package. Everything which is related to how the swagger definition is built has to be done in fastify-swagger

**Comment by jschuur** [comment]
> I dont think that this is related to this package. Everything which is related to how the swagger definition is built has to be done in fastify-swagger

Thanks for clarifying. I've gone ahead and opened a [help issue](https://github.com/fastify/help/issues/779) instead about this.

I suspect my issue is that I'm defining my response options via JSON schema because that's how I pass them into my fastify routes, and not in the `paths` endpoint definitions that I send to fastify-swagger, which supports the `example` object format.

Just not sure what the solution is... do I just duplicate the definitions, one via `paths` and one via my route definitions and hope that fastify-swagger is smart enough to figure out which one to use?

Will defer to that thread for a discussion...
