### ISSUE TITLE
uiConfig cant handle functions

### ISSUE THREAD

**Issue by nada-one** [fastify/fastify-swagger-ui#25]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello!

Firstly, thanks for an awesome package! Such a huge help. 

I got a question and I am hoping you can help me out on this. I am not quite sure but it seems that preauthorizeBasic and preauthorizeApiKey instance methods as documented in https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md are not yet supported by the package. 

Are these options something that you plan to support in the future? If I overlooked it and that they're already supported, can you please provide an example on how I can pass them?

In swagger-ui-express, I am able to utilize the onComplete parameter to pass a function that invokes those instance methods as shown below:
 {
           tagsSorter: 'alpha',
            **onComplete: function () {
                    ui.preauthorizeBasic("basicAuth", "user", "pass");
                    ui.preauthorizeApiKey("apiKey", "apikey");
            }**   
}

Thanks for the feedback in advance!

**Comment by nada-one** [comment]
Tried passing the following to uiConfig but it doesn't work:

onComplete: function () {
   ui.preauthorizeBasic("basicAuth", "user", "pass");
   ui.preauthorizeApiKey("apiKey", "apikey");
}

I ended up adding some custom code to achieve this in swagger-initializer.js.

**Comment by climba03003** [comment]
`swagger-ui-express` is dynamic generate the `JavaScript` where as we statically provide the `JavaScript`.

I don't think `.toString` a function would be good and it somehow prone to error since people may think that variable will work inside the function.

**Comment by Uzlopak** [comment]
The issue is that the uiConfig is serialized to json and supplied by a rest-call. And functions cant be serialized.

So we have to find a way to provide the functions in a javascript file or somehow differently...
