### ISSUE TITLE
Swagger themes support

### ISSUE THREAD

**Issue by OkanPinar** [fastify/fastify-swagger-ui#35]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Integration with different styles can be good for customization. The following repository could be helpful.

https://www.npmjs.com/package/swagger-themes

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
