### ISSUE TITLE
Custom CSS Theme

### ISSUE THREAD

**Issue by ilyamixaltik** [fastify/fastify-swagger-ui#38]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Good time of day. I tried to find an opportunity to connect a custom CSS file (a theme for Swagger), but unfortunately I didn't find it. Is there such a possibility? If not, is it planned?

**Comment by mcollina** [comment]
I would really love support for this too.

**Comment by ilyamixaltik** [comment]
@mcollina the fact is that I am the developer of the "swagger-theme" library. And now the question has arisen about the support of Fastify. But unfortunately, I was unable to connect the library.
