### ISSUE TITLE
Favicon Content Buffer

### ISSUE THREAD

**Issue by ivanjrcomp** [fastify/fastify-swagger-ui#50]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to propose that the favicon theme property be updated to allow for the use of a Buffer object, similar to the logo configuration parameter in @fastify/swagger-ui version 1.6.0.

### Motivation

Currently, the favicon theme property only accepts a string, while the logo configuration parameter can accept a Buffer object. However, when I try to pass a Buffer object to the favicon content, it causes an issue in VSCode that says it needs to be assigned as a string. When I convert it to a string, the favicon no longer appears.

Allowing the favicon theme property to accept a Buffer object would be consistent with the logo configuration parameter and would enable greater flexibility in customizing the favicon. 

Thank you for considering this proposal.

### Example

```const buffer = fs.readFileSync('favicon.png', 'base64')

app.register(fastifySwaggerUi, {
  routePrefix: '/docs',
  theme: {
    js: [{ filename: 'special.js', content: 'alert("loaded test-theme")' }],
    css: [{ filename: 'theme.css', content: '* {border: 1px red solid;}' }],
    favicon: [
      {
        filename: 'favicon.png',
        rel: 'icon',
        sizes: '16x16',
        type: 'image/png',
        content: Buffer.from(
          buffer,
          'base64',
        ),
      },
    ],
  }, 
  uiConfig: {
    deepLinking: true,
    showExtensions: true,
    displayRequestDuration: true,
    docExpansion: 'list',
    withCredentials: true,
  },
})
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mdoria12** [comment]
Hi, i'm not sure but i think it already support Buffer in the code, i think the problem is only in the types definition that allows only string. [here](https://github.com/fastify/fastify-swagger-ui/blob/master/types/index.d.ts#L65)

I tried to bypass the types check and set directly a buffer this way and it works for me

```
const favicon16x16: any = await readFile(
   resolve('./static/favicon-16x16.png')
);
        
// then in the  settings ...
        
favicon: [
      {
        filename: 'favicon.png',
        rel: 'icon',
        sizes: '16x16',
        type: 'image/png',
        content: favicon16x16
      },
],
        
```

Honestly i tried also by passing directly the base64 string (`await readFile(resolve('./static/favicon-16x16.png'),'base64');`) but the icon does not appear, so i do not know if this is a bug or i'm doing something wrong when trying to pass a string content.

**Comment by mcollina** [comment]
A PR would be awesome.

**Comment by mdoria12** [comment]
@mcollina done https://github.com/fastify/fastify-swagger-ui/pull/52
It's my first contribution so if something is missing or wrong please give me advise
