### ISSUE TITLE
Customize Browser Tab Title

### ISSUE THREAD

**Issue by sceccotti89** [fastify/fastify-swagger-ui#53]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I would like to be able to customize the Browser tab title in order to show something different than the default "Swagger UI".

### Motivation

In one of my project I'm working with multiple Swaggers and I would like to be able to distinguish them showing different tab names.

### Example

```js
app.register(fastifySwaggerUi, {
  routePrefix: '/docs',
  theme: {
    title: 'My Custom Swagger Title'
  }, 
  uiConfig: {
    deepLinking: true,
    showExtensions: true,
    displayRequestDuration: true,
    docExpansion: 'list',
    withCredentials: true,
  },
})
```

I'm not entirely sure it should be part of the `theme` section, but I'm open for a discussion.

**Comment by mcollina** [comment]
I think this should be part of the theme section and that implementation.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by sceccotti89** [comment]
@mcollina Sure, I'll open a PR once I have a bit of time (probably beginning of the next week).
I also noticed that when I have multiple swaggers the tab icon is not shown properly. Should I open a different PR for that or it can be part of the same?
<img width="223" alt="Screenshot 2023-04-05 at 13 11 24" src="https://user-images.githubusercontent.com/10226735/230064020-627ea0b8-94d9-4627-ae1c-46e6ba17425f.png">

**Comment by sceccotti89** [comment]
@mcollina I've found it easier than I thought to customize it. PR ready here: https://github.com/fastify/fastify-swagger-ui/pull/54
