### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by BCsabaEngine** [fastify/fastify-swagger-ui#7]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.8.1

### Plugin version

8.0.0

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

I cannot install ```npm i @fastify/swagger-ui```, npmjs does not contains info about thhis package.

### Steps to Reproduce

npm i @fastify/swagger
npm i @fastify/swagger-ui

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fastify%2fswagger-ui - Not found
npm ERR! 404 
npm ERR! 404  '@fastify/swagger-ui@*' is not in this registry.

### Expected Behavior

Install package

**Comment by Uzlopak** [comment]
Hi, i contacted already @mcollina . He wrote me to release it asap but it might be tomorrow. 

I apologize for the inconvenience.
