### ISSUE TITLE
Update for swagger-ui v5.1.0

### ISSUE THREAD

**Issue by qqilihq** [fastify/fastify-swagger-ui#71]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Could you release an update for the recently released swagger-ui [v5.1.0](https://github.com/swagger-api/swagger-ui/releases/tag/v5.1.0)?

**Comment by mcollina** [comment]
Done

**Comment by qqilihq** [comment]
That was fast - thanks a buch!
