### ISSUE TITLE
The Swagger UI is failing to display any content on the Amazon EC2 instance. 

### ISSUE THREAD

**Issue by hanancs** [fastify/fastify-swagger-ui#74]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

1.8.0

### Node.js version

18.15.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.3.1 (a) 

### Description

A Node.js application utilizing the Fastify framework, and api is documented using "fastify-swagger" and "fastify-swagger-ui". The Swagger UI loads seamlessly on my local server at "localhost:3000/v1/docs" and operates without any issues.

However, when I deployed the application to an Amazon EC2 instance (running on Amazon Linux), I encountered a problem. Although all APIs function correctly on the server, navigating to "myamazonurl.com/docs/static/index.html" redirects me to the Swagger UI, which, unfortunately, does not display anything.

The console and network are both displaying errors that seem identical. 

### Steps to Reproduce

- Develop a Node.js Application: Firstly, develop a Node.js application using the Fastify framework.

- Document using fastify-swagger and fastify-swagger-ui: After developing the application, proceed to document it using "fastify-swagger" and "fastify-swagger-ui".

- Test on Local Server: Run the application on your local server and access the Swagger UI by navigating to "localhost:3000/docs/static/index.html". Check if it is working properly.

- Deploy the Application on Amazon EC2 Instance: Now, deploy the application to an Amazon EC2 instance (running Amazon Linux).

- Test APIs: After deploying, check if all APIs are hitting the server correctly and functioning as expected.

- Access Swagger UI on EC2 Instance: Finally, attempt to access the Swagger UI on the EC2 instance by visiting "myamazonurl.com/docs/static/index.html". The issue occurs here, as it redirects to the Swagger UI, but nothing is displayed.

- Check Console and Network Errors: Inspect the console and network for any errors. The same errors seem to appear on both.

I have attached these errors for further clarification.

<img width="1440" alt="image" src="https://github.com/fastify/fastify-swagger-ui/assets/50701475/2b2dce37-18d4-462b-8ab0-98887a25488c">

### Expected Behavior

Swagger UI should be accessible and displayed correctly on the EC2 instance, and the server itself should not force itself to find resources(Swagger resources) on the HTTPS scheme.

<img width="1440" alt="image" src="https://github.com/fastify/fastify-swagger-ui/assets/50701475/8a35ca3b-7acd-4b8c-a691-384aaa7a460e">

**Comment by mcollina** [comment]
Thanks for reporting!

Unfortunately, the steps you are providing are far from being useful to diagnose and debug this. We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by jsumners** [comment]
Sounds similar to https://github.com/fastify/fastify-swagger/issues/397

**Comment by maioranoknobs** [comment]
Does anyone have a solution to this problem? I'm having the same problem with swagger ui, locally it works correctly but when I deploy on AWS Cloudformation (i'm using fastify lambda) I get the 504 Gateway Timeout error. There is a way to resolve this error?

This is my own configuration:


`const registerSwaggerPlugin = async (server: FastifyInstance) => {

  server.register(swagger, {
    swagger: {
      info: {
        title: "Backend swagger",
        description: "Swagger for Backend API",
        version: "0.1.0",
      },
      externalDocs: {
        url: "https://swagger.io",
        description: "Find more swagger info here",
      },
      host: "localhost:3000",
      schemes: ["http"],
      consumes: ["application/json"],
      produces: ["application/json"],
      securityDefinitions: {
        apiKey: {
          type: "apiKey",
          name: "apiKey",
          in: "header",
        },
      },
    },
  });

  server.register(swaggerUi, {
    routePrefix: '/docs',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: false
    },
    uiHooks: {
      onRequest: function (request, reply, next) { next() },
      preHandler: function (request, reply, next) { next() }
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
    transformSpecification: (swaggerObject, request, reply) => { return swaggerObject },
    transformSpecificationClone: true
  });

}`

**Comment by jnixon2** [comment]
I also seem to be getting the same issue with AWS lambda, works fine locally but then when coming through lambda and Apigateway I get a blank page.

**Comment by maioranoknobs** [comment]
In my case I solved the problem by increasing the API_TIMEOUT parameter. I set a generic timeout on my API so that they would respond with a 504 in case the server did not respond within a certain time, i think that due to the cold start of the lambda function the call to the /docs/static/index.html page took longer than the API_TIMEOUT and therefore didn't render the page correctly, I hope it helps

```
const setAppTimeout = async (server: FastifyInstance) => {

  await server.addHook('onRequest', (request, response, done) => {
    const timeoutMs = parseInt(process.env.API_TIMEOUT!, 10);
    // Check if the response has already been sent
    if (response.sent) {
      done();
      return;
    }
    setTimeout(() => {
      // Check again if the response was already sent before sending it again
      if (!response.sent) {
        httpResponse.handleTimeoutServerError(response, "Timeout error: The request took too long to process.");
      }
    }, timeoutMs);
    done();
  });

}
```

**Comment by davidjbng** [comment]
> I have attached these errors for further clarification.
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/50701475/253722581-2b2dce37-18d4-462b-8ab0-98887a25488c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTU0NjUsIm5iZiI6MTcwMTg1NTE2NSwicGF0aCI6Ii81MDcwMTQ3NS8yNTM3MjI1ODEtMmIyZGNlMzctMThkNC00NjJiLThhYjAtOTg4ODdhMjU0ODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMDA1ZjUzNzJhOTM1YTQ1NTI0OWVlYjljODA5NGQwYzA4MmIzYmFlNjA3NTkxMDk2MDkxODNiODU3MTFmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C3FxTy4tQVVGm-j9FTaXcaL1rtYT010T4N7knXHaOg8">
> ### Expected Behavior
> Swagger UI should be accessible and displayed correctly on the EC2 instance, and the server itself should not force itself to find resources(Swagger resources) on the HTTPS scheme.
> 
> <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/50701475/253723750-8a35ca3b-7acd-4b8c-a691-384aaa7a460e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTU0NjUsIm5iZiI6MTcwMTg1NTE2NSwicGF0aCI6Ii81MDcwMTQ3NS8yNTM3MjM3NTAtOGEzNWNhM2ItN2FjZC00YjhjLWE2OTEtMzg0YWFhN2E0NjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDI5ZDVlYmFmOWVjYzNhMmRjNWNhNjgzMGVmZWQ5MGRkNjkwYTFlM2Q0MDliYzg4Y2Q4ZGJjNmMyMzYxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KoFx1unTOBmLe9ZBKzrfTCuJNLlA-4yyY2z1_d4M8Uc">

Can you confirm that the static assets are available on your server? Do you bundle your api?
Looks similar to #65 to me.

**Comment by phabreeze** [comment]
Having the exact same issue when running behind Azure API Management. It looks like all subdirectories in between the domain and `/documentation/` are being removed, e.g. `https://something.com/my-api/documentation` redirects to `https://something.com/documentation`

**Comment by climba03003** [comment]
> Having the exact same issue when running behind Azure API Management. It looks like all subdirectories in between the domain and `/documentation/` are being removed, e.g. `https://something.com/my-api/documentation` redirects to `https://something.com/documentation`

Please try `4.1.0` version for your case.

**Comment by hanancs** [comment]
The issue is not related to the EC2 instance but to the absence of SSL (HTTPS) on your DNS configuration. Swagger UI requires SSL when accessed over a live domain. It works on localhost without SSL, but in a live environment, Swagger UI must be accessed via HTTPS.

To resolve this, configure SSL for your domain to ensure the Swagger UI loads correctly in production.
